added tests for solar system component
developer-kaczmarek/EducationSpace pull request #12
Opened 2022-03-16 15:01 UTC by developer-kaczmarek

replace realm to room
created RoomDatabaseFactory
added tests for SolarSystemComponent

2022-03-17 12:39 UTC, aartikov requested changes

2022-03-17 12:39 UTC, aartikov commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/app_theme/AppThemeComponentTest.kt
> +@Config(manifest = Config.NONE)
Расскажи, что делает аннотация Config?

2022-03-17 12:39 UTC, aartikov commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/solar_system/SolarSystemPlanetsComponentTest.kt
> +        Thread.sleep(200)
Непонятно, зачем нужен sleep. По коду ожидаешь, что второй awaitUntil и так дождется нужного состояния

2022-03-17 12:39 UTC, aartikov commented on app/build.gradle
> +            includeAndroidResources = true
Расскажи, что этот флаг делает

2022-03-18 07:16 UTC, developer-kaczmarek commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/app_theme/AppThemeComponentTest.kt
> +@Config(manifest = Config.NONE)
Данная аннотация используется для [настройки Robolectric](http://robolectric.org/configuring/#:~:text=To%20configure%20Robolectric%20for%20a,specified%20at%20the%20class%20level.). Позволяет переопределять некоторые значения.

2022-03-18 07:34 UTC, developer-kaczmarek commented on app/build.gradle
> +            includeAndroidResources = true
Наши тесты работают в пространстве модульных тестов. Для того, чтобы [robolectric работал нормально](http://robolectric.org/getting-started/) необходимо добавить данный [флаг](https://google.github.io/android-gradle-dsl/3.0/com.android.build.gradle.internal.dsl.TestOptions.UnitTestOptions.html).  Фактически данный флаг позволяет модульным тестам использовать ресурсы и манифесты Android. Добавление данного флага исправило проблемы создания БД типа inMemory в тестах

2022-03-18 07:35 UTC, developer-kaczmarek commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/solar_system/SolarSystemPlanetsComponentTest.kt
> +        Thread.sleep(200)
Согласна, однако не дожидается. Если удалить sleep в логах можно увидеть данное предупреждение: 
`Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.`

2022-03-18 08:05 UTC, aartikov commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/solar_system/SolarSystemPlanetsComponentTest.kt
> +        Thread.sleep(200)
Хм, у меня даже со sleep-ом тест не проходит:

```
Condition with lambda expression in org.awaitility.kotlin.AwaitilityKt that uses kotlin.jvm.functions.Function0 was not fulfilled within 10 seconds.
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.awaitility.kotlin.AwaitilityKt that uses kotlin.jvm.functions.Function0 was not fulfilled within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
	at org.awaitility.kotlin.AwaitilityKt.until(AwaitilityKt.kt:138)
	at io.github.kaczmarek.educationspace.utils.AwaitilityUtilsKt.awaitUntil(AwaitilityUtils.kt:10)
	at io.github.kaczmarek.educationspace.solar_system.SolarSystemPlanetsComponentTest.shows data when it is loaded(SolarSystemPlanetsComponentTest.kt:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
```

2022-03-18 08:08 UTC, developer-kaczmarek commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/solar_system/SolarSystemPlanetsComponentTest.kt
> +        Thread.sleep(200)
Поняла, буду дорабатывать этот тест

2022-03-18 08:22 UTC, aartikov commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/solar_system/SolarSystemPlanetsComponentTest.kt
> +        Thread.sleep(200)
Не понятно, почему роболектрик выдает ворнинг, ведь мы вызываем Shadows.shadowOf(Looper.getMainLooper()).idle() в awaitUntil

2022-03-21 12:44 UTC, developer-kaczmarek commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/solar_system/SolarSystemPlanetsComponentTest.kt
> +        Thread.sleep(200)
Это исправлено, я покопалась в доке. С Room в тестах советуют работать в Main потоке, а когда Room работает в main необходимо добавлять allowMainThreadQueries() иначе она выбросит исключение.

2022-03-21 12:44 UTC, developer-kaczmarek commented on app/src/test/kotlin/io/github/kaczmarek/educationspace/solar_system/SolarSystemPlanetsComponentTest.kt
> +        Thread.sleep(200)
Это исправлено, я покопалась в доке. С Room в тестах советуют работать в Main потоке, а когда Room работает в main необходимо добавлять allowMainThreadQueries() иначе она выбросит исключение.

2022-03-22 08:11 UTC, merged